version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    git submodule init

    git submodule update

    cmake CMakeLists.txt

    make

    g++ -std=c++17 -o2 -Ieigen main_ad.cpp -o main_ad

    g++ -pthread -std=c++17 -o2 main_mc.cpp -o main_mc

test_script:
- sh: >-
    ./Tests/unit_tests
