version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    git submodule init
    
    git submodule update

    cmake CMakeLists.txt
    
    make
    
    ctest
    
    ./mcml/tests/unit_tests
